// <auto-generated />
using System;
using Consultas.ServiceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consultas.ServiceAPI.Migrations
{
    [DbContext(typeof(ConsultasDbContext))]
    partial class ConsultasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Consultas.ServiceAPI.Domain.Consulta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<long>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicoNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PacienteCpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PacienteNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("consultas");
                });

            modelBuilder.Entity("Consultas.ServiceAPI.Domain.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CRM")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConsultaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataReceita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<long>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicoNome")
                        .HasColumnType("TEXT");

                    b.Property<long>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PacienteNome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("Consultas.ServiceAPI.Domain.Receita", b =>
                {
                    b.HasOne("Consultas.ServiceAPI.Domain.Consulta", "Consulta")
                        .WithMany("Receitas")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Consultas.ServiceAPI.Domain.Consulta", b =>
                {
                    b.Navigation("Receitas");
                });
#pragma warning restore 612, 618
        }
    }
}
